### ISSUE TITLE
Move to multi-stage build for container-features

### ISSUE THREAD

**Issue by stuartleeks** [devcontainers/cli#10]
This issue proposes moving the container-features build over to using a multi-stage docker build.

Prior to container-features, it was possible to build the dev container image with an inline cache manifest, push it to a registry and then reference that image in the `cacheFrom` in `devcontainer.json` (or in `cache_from` in `docker-compose.yml`) to have the registry image used as a layer cache.
When using container-features, there are now two images built, so you would need to push two images to the registry and reference two images in the `cacheFrom`.

Making this change will result in a single image build step for the container which will allow for pushing the resulting image to a registry complete with an inline cache manifest, making it possible to get back to the single dev container image that works for image caching.

Anticipated steps:
- [X]  Combine extendImage into build function for Dockerfile #9 
- [X] Update Dockerfile build to use multi-stage build with container-features #13
- [ ] Combine `extendImage` into build function for docker-compose and update docker-compose build to use multi-stage build with container-features (#38)
